apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app-deployment-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app-2
  template:
    metadata:
      labels:
        app: web-app-2
    spec:
      containers:
      - name: web-app-2
        image: devopsaks20/web-server:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-svc-2
spec:
  selector:
    app: web-app-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

