apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: my-python-app
        image: devopsaks20/python-app-ci-cd:tag
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
# adding HPA
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: python-app
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-app
  targetCPUUtilizationPercentage: 30 # target CPU utilization
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
